CREATE TABLE ANNEXE (
	ID    int(11) PRIMARY KEY NOT NULL,
	NAME  varchar(50) NOT NULL,
	TYPE  varchar(100) NOT NULL,
	SIZE  int(11),
  FILE  blob NOT NULL
	);

CREATE INDEX annexe_pkey ON annexe (id);

CREATE TABLE PUBLIC.DEMANDE_AUTORISATION (
	ID int(11) PRIMARY KEY NOT NULL,
	PROFESSIONDELASANTE int(11),
	STATUTDEMANDEAUTORISATION int(11)
);

CREATE INDEX demande_autorisation_pkey ON demande_autorisation (ID);