CREATE TABLE ANNEXE (
	ID BIGINT NOT NULL,
	TYPEANNEXE SMALLINT,
	VERSION INTEGER,
	CONTENU BLOB,
	TAILLE BIGINT,
	NOMFICHIER VARCHAR(255),
	DEMANDE_ID BIGINT,
	CONSTRAINT CONSTRAINT_ANNEXE_PKEY PRIMARY KEY (ID)
);

CREATE INDEX PRIMARY_KEY_ANNEXE ON ANNEXE (ID);

CREATE TABLE DEMANDE_AUTORISATION (
	ID BIGINT NOT NULL,
	PROFESSIONDELASANTE SMALLINT,
	STATUTDEMANDEAUTORISATION SMALLINT,
	VERSION INTEGER,
	REFERENCE VARCHAR(255),
	CONSTRAINT CONSTRAINT_DEMANDE_AUTORISATION_PKEY PRIMARY KEY (ID)
);

CREATE INDEX INDEX_KEY_DEMANDE ON DEMANDE_AUTORISATION (ID);




