CREATE TABLE DEMANDE_AUTORISATION (id BIGINT NOT NULL, professionDeLaSante SMALLINT, reference INTEGER, statutDemandeAutorisation SMALLINT, PRIMARY KEY (id));
CREATE TABLE OPENJPA_SEQUENCE_TABLE (ID TINYINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));
