CREATE TABLE Annexe (id BIGINT NOT NULL, typeAnnexe VARCHAR(20), ANNEXES_ID BIGINT, PRIMARY KEY (id));
CREATE TABLE DEMANDE (id BIGINT NOT NULL, DTYPE VARCHAR(255), version INTEGER, professionDeLaSante VARCHAR(32), statutDemandeAutorisation VARCHAR(20), login VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE OPENJPA_SEQUENCE_TABLE (ID TINYINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));
CREATE TABLE UTILISATEUR (id BIGINT NOT NULL, version INTEGER, login VARCHAR(255), PRIMARY KEY (id));
CREATE INDEX I_DEMANDE_DTYPE ON DEMANDE (DTYPE);
