CREATE TABLE Annexe (id BIGINT NOT NULL, typeAnnexe VARCHAR(20), ANNEXES_ID BIGINT, PRIMARY KEY (id));
CREATE TABLE DEMANDE (id BIGINT NOT NULL, DTYPE VARCHAR(255), version INTEGER, reference VARCHAR(255), professionDeLaSante VARCHAR(32), statutDemandeAutorisation VARCHAR(20), DEMANDEUR_ID BIGINT, PRIMARY KEY (id));
CREATE TABLE DEMANDEUR (id BIGINT NOT NULL, version INTEGER, value VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE OPENJPA_SEQUENCE_TABLE (ID TINYINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));
CREATE INDEX I_DEMANDE_DEMANDEUR ON DEMANDE (DEMANDEUR_ID);
CREATE INDEX I_DEMANDE_DTYPE ON DEMANDE (DTYPE);
