CREATE TABLE ANNEXE (id BIGINT NOT NULL, typeAnnexe SMALLINT, VERSION INTEGER, contenu BLOB, taille BIGINT, nomFichier VARCHAR(255), DEMANDE_ID BIGINT, PRIMARY KEY (id));
CREATE TABLE DEMANDE_AUTORISATION (id BIGINT NOT NULL, professionDeLaSante SMALLINT, statutDemandeAutorisation SMALLINT, VERSION INTEGER, reference VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE OPENJPA_SEQUENCE_TABLE (ID TINYINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));

