package ch.vd.demaut.domain.demandeur;

import ch.vd.demaut.domain.config.RefProgresID;
import ch.vd.demaut.domain.config.TypeProgres;
import ch.vd.demaut.domain.demandeur.donneesProf.diplome.TypeDiplomeNotFoundException;

public enum Pays implements TypeProgres {
    ListeIncomplete(0, "Incomplète", "Liste incomplète..."),
    Afghanistan(2, "AF", "Afghanistan"),
    AfriqueDuSud(3, "ZA", "Afrique du Sud"),
    Albanie(4, "AL", "Albanie"),
    Algerie(5, "DZ", "Algérie"),
    Allemagne(6, "DE", "Allemagne"),
    Andorre(7, "AD", "Andorre"),
    Angola(8, "AO", "Angola"),
    Anguilla(9, "AI", "Anguilla"),
    Antarctique(10, "AQ", "Antarctique"),
    AntiguaEtBarbuda(11, "AG", "Antigua-et-Barbuda"),
    AntillesNeerlandaises(12, "AN", "Antilles néerlandaises"),
    ArabieSaoudite(13, "SA", "Arabie saoudite"),
    Argentine(14, "AR", "Argentine"),
    Armenie(15, "AM", "Arménie"),
    Aruba(16, "AW", "Aruba"),
    Australie(17, "AU", "Australie"),
    Autriche(18, "AT", "Autriche"),
    Azerbaidjan(19, "AZ", "Azerbaïdjan"),
    Bahamas(20, "BS", "Bahamas"),
    Bahrein(21, "BH", "Bahreïn"),
    Bangladesh(22, "BD", "Bangladesh"),
    Barbade(23, "BB", "Barbade"),
    Belgique(24, "BE", "Belgique"),
    Belize(25, "BZ", "Belize"),
    Bermudes(26, "BM", "Bermudes"),
    Bhoutan(27, "BT", "Bhoutan"),
    Bolivie(28, "BO", "Bolivie"),
    BosnieHerzegovine(29, "BA", "Bosnie-Herzégovine"),
    Botswana(30, "BW", "Botswana"),
    BruneiDarussalam(31, "BN", "Brunéi Darussalam"),
    Bresil(32, "BR", "Brésil"),
    Bulgarie(33, "BG", "Bulgarie"),
    BurkinaFaso(34, "BF", "Burkina Faso"),
    Burundi(35, "BI", "Burundi"),
    Belarus(36, "BY", "Bélarus"),
    Benin(37, "BJ", "Bénin"),
    Cambodge(38, "KH", "Cambodge"),
    Cameroun(39, "CM", "Cameroun"),
    Canada(40, "CA", "Canada"),
    CapVert(41, "CV", "Cap-Vert"),
    Chili(42, "CL", "Chili"),
    Chine(43, "CN", "Chine"),
    Chypre(44, "CY", "Chypre"),
    Colombie(45, "CO", "Colombie"),
    Comores(46, "KM", "Comores"),
    Congo(47, "CG", "Congo"),
    CoreeDuNord(48, "KP", "Corée du Nord"),
    // TODO completer la liste
//            (49, "KR", "Corée du Sud");
//            (50, "CR", "Costa Rica"),
//            (51, "HR", "Croatie"),
//            (52, "CU", "Cuba"),
//            (53, "CI", "Côte d?Ivoire"),
//            (54, "DK", "Danemark"),
//            (55, "DJ", "Djibouti"),
//            (56, "DM", "Dominique"),
//            (57, "SV", "El Salvador"),
//            (58, "ES", "Espagne"),
//            (59, "EE", "Estonie"),
//            (60, "FJ", "Fidji"),
//            (61, "FI", "Finlande"),
//            (62, "FR", "France"),
//            (63, "GA", "Gabon"),
//            (64, "GM", "Gambie"),
//            (65, "GH", "Ghana"),
//            (66, "GI", "Gibraltar"),
//            (67, "GD", "Grenade"),
//            (68, "GL", "Groenland"),
//            (69, "GR", "Grèce"),
//            (70, "GP", "Guadeloupe"),
//            (71, "GU", "Guam"),
//            (72, "GT", "Guatemala"),
//            (73, "GG", "Guernesey"),
//            (74, "GN", "Guinée"),
//            (75, "GQ", "Guinée équatoriale"),
//            (76, "GW", "Guinée-Bissau"),
//            (77, "GY", "Guyana"),
//            (78, "GF", "Guyane française"),
//            (79, "GE", "Géorgie"),
//            (80, "GS", "Géorgie du Sud et les îles Sandwich du Sud"),
//            (81, "HT", "Haïti"),
//            (82, "HN", "Honduras"),
//            (83, "HU", "Hongrie"),
//            (84, "IN", "Inde"),
//            (85, "ID", "Indonésie"),
//            (86, "IQ", "Irak"),
//            (87, "IR", "Iran"),
//            (88, "IE", "Irlande"),
//            (89, "IS", "Islande"),
//            (90, "IL", "Israël"),
//            (91, "IT", "Italie"),
//            (92, "JM", "Jamaïque"),
//            (93, "JP", "Japon"),
//            (94, "JE", "Jersey"),
//            (95, "JO", "Jordanie"),
//            (96, "KZ", "Kazakhstan"),
//            (97, "KE", "Kenya"),
//            (98, "KG", "Kirghizistan"),
//            (99, "KI", "Kiribati"),
//            (100, "KW", "Koweït"),
//            (101, "LA", "Laos"),
//            (102, "LS", "Lesotho"),
//            (103, "LV", "Lettonie"),
//            (104, "LB", "Liban"),
//            (105, "LY", "Libye"),
//            (106, "LR", "Libéria"),
//            (107, "LI", "Liechtenstein"),
//            (108, "LT", "Lituanie"),
//            (109, "LU", "Luxembourg"),
//            (110, "MK", "Macédoine"),
//            (111, "MG", "Madagascar"),
//            (112, "MY", "Malaisie"),
//            (113, "MW", "Malawi"),
//            (114, "MV", "Maldives"),
//            (115, "ML", "Mali"),
//            (116, "MT", "Malte"),
//            (117, "MA", "Maroc"),
//            (118, "MQ", "Martinique"),
//            (119, "MU", "Maurice"),
//            (120, "MR", "Mauritanie"),
//            (121, "YT", "Mayotte"),
//            (122, "MX", "Mexique"),
//            (123, "MD", "Moldavie"),
//            (124, "MC", "Monaco"),
//            (125, "MN", "Mongolie"),
//            (126, "MS", "Montserrat"),
//            (127, "ME", "Monténégro"),
//            (128, "MZ", "Mozambique"),
//            (129, "MM", "Myanmar"),
//            (130, "NA", "Namibie"),
//            (131, "NR", "Nauru"),
//            (132, "NI", "Nicaragua"),
//            (133, "NE", "Niger"),
//            (134, "NG", "Nigéria"),
//            (135, "NU", "Niue"),
//            (136, "NO", "Norvège"),
//            (137, "NC", "Nouvelle-Calédonie"),
//            (138, "NZ", "Nouvelle-Zélande"),
//            (139, "NP", "Népal"),
//            (140, "OM", "Oman"),
//            (141, "UG", "Ouganda"),
//            (142, "UZ", "Ouzbékistan"),
//            (143, "PK", "Pakistan"),
//            (144, "PW", "Palaos"),
//            (145, "PA", "Panama"),
//            (146, "PG", "Papouasie-Nouvelle-Guinée"),
//            (147, "PY", "Paraguay"),
//            (148, "NL", "Pays-Bas"),
//            (149, "PH", "Philippines"),
//            (150, "PN", "Pitcairn"),
//            (151, "PL", "Pologne"),
//            (152, "PF", "Polynésie française"),
//            (153, "PR", "Porto Rico"),
//            (154, "PT", "Portugal"),
//            (155, "PE", "Pérou"),
//            (156, "QA", "Qatar"),
//            (157, "HK", "R.A.S. chinoise de Hong Kong"),
//            (158, "MO", "R.A.S. chinoise de Macao"),
//            (159, "RO", "Roumanie"),
//            (160, "GB", "Royaume-Uni"),
//            (161, "RU", "Russie"),
//            (162, "RW", "Rwanda"),
//            (163, "CF", "République centrafricaine"),
//            (164, "DO", "République dominicaine"),
//            (165, "CD", "République démocratique du Congo"),
//            (166, "CZ", "République tchèque"),
//            (167, "RE", "Réunion"),
//            (168, "EH", "Sahara occidental"),
//            (169, "BL", "Saint-Barthélémy"),
//            (170, "KN", "Saint-Kitts-et-Nevis"),
//            (171, "SM", "Saint-Marin"),
//            (172, "MF", "Saint-Martin"),
//            (173, "PM", "Saint-Pierre-et-Miquelon"),
//            (174, "VC", "Saint-Vincent-et-les Grenadines"),
//            (175, "SH", "Sainte-Hélène"),
//            (176, "LC", "Sainte-Lucie"),
//            (177, "WS", "Samoa"),
//            (178, "AS", "Samoa américaines"),
//            (179, "ST", "Sao Tomé-et-Principe"),
//            (180, "RS", "Serbie"),
//            (181, "CS", "Serbie-et-Monténégro"),
//            (182, "SC", "Seychelles"),
//            (183, "SL", "Sierra Leone"),
//            (184, "SG", "Singapour"),
//            (185, "SK", "Slovaquie"),
//            (186, "SI", "Slovénie"),
//            (187, "SO", "Somalie"),
//            (188, "SD", "Soudan"),
//            (189, "LK", "Sri Lanka"),
    Suisse(190, "CH", "Suisse");
//            (191, "SR", "Suriname"),
//            (192, "SE", "Suède"),
//            (193, "SJ", "Svalbard et Île Jan Mayen"),
//            (194, "SZ", "Swaziland"),
//            (195, "SY", "Syrie"),
//            (196, "SN", "Sénégal"),
//            (197, "TJ", "Tadjikistan"),
//            (198, "TZ", "Tanzanie"),
//            (199, "TW", "Taïwan"),
//            (200, "TD", "Tchad"),
//            (201, "TF", "Terres australes françaises"),
//            (202, "IO", "Territoire britannique de l'océan Indien"),
//            (203, "PS", "Territoire palestinien"),
//            (204, "TH", "Thaïlande"),
//            (205, "TL", "Timor oriental"),
//            (206, "TG", "Togo"),
//            (207, "TK", "Tokelau"),
//            (208, "TO", "Tonga"),
//            (209, "TT", "Trinité-et-Tobago"),
//            (210, "TN", "Tunisie"),
//            (211, "TM", "Turkménistan"),
//            (212, "TR", "Turquie"),
//            (213, "TV", "Tuvalu"),
//            (214, "UA", "Ukraine"),
//            (215, "UY", "Uruguay"),
//            (216, "VU", "Vanuatu"),
//            (217, "VE", "Venezuela"),
//            (218, "VN", "Viêt Nam"),
//            (219, "WF", "Wallis-et-Futuna"),
//            (220, "YE", "Yémen"),
//            (221, "ZM", "Zambie"),
//            (222, "ZW", "Zimbabwe"),
//            (223, "ZZ", "région indéterminée"),
//            (224, "EG", "Égypte"),
//            (225, "AE", "Émirats arabes unis"),
//            (226, "EC", "Équateur"),
//            (227, "ER", "Érythrée"),
//            (228, "VA", "État de la Cité du Vatican"),
//            (229, "FM", "États fédérés de Micronésie"),
//            (230, "US", "États-Unis"),
//            (231, "ET", "Éthiopie"),
//            (232, "BV", "Île Bouvet"),
//            (233, "CX", "Île Christmas"),
//            (234, "NF", "Île Norfolk"),
//            (235, "IM", "Île de Man"),
//            (236, "KY", "Îles Caïmans"),
//            (237, "CC", "Îles Cocos - Keeling"),
//            (238, "CK", "Îles Cook"),
//            (239, "FO", "Îles Féroé"),
//            (240, "HM", "Îles Heard et MacDonald"),
//            (241, "FK", "Îles Malouines"),
//            (242, "MP", "Îles Mariannes du Nord"),
//            (243, "MH", "Îles Marshall"),
//            (244, "UM", "Îles Mineures Éloignées des États-Unis"),
//            (245, "SB", "Îles Salomon"),
//            (246, "TC", "Îles Turks et Caïques"),
//            (247, "VG", "Îles Vierges britanniques"),
//            (248, "VI", "Îles Vierges des États-Unis"),
//            (249, "AX", "Îles Åland");


    private RefProgresID progresId;

    private String libl;

    private String code;

    private Pays(Integer id, String code, String libl) {
        this.progresId = new RefProgresID(id);
        this.libl = libl;
        this.code = code;
    }

    static public Pays getTypeById(Integer id2) {
        for (Pays type : Pays.values()) {
            if (type.getRefProgresID().equals(new RefProgresID(id2))) {
                return type;
            }
        }
        throw new TypeDiplomeNotFoundException();
    }

    public RefProgresID getRefProgresID() {
        return progresId;
    }

    public String getLibl() {
        return libl;
    }

    public String getCode() {
        return code;
    }
}
